// src/components/ui/Icon.jsx
// ─────────────────────────────────────────────────────────
// Composant icône centralisé — Lucide (outlined, stroke 2px)
// Remplace Phosphor + Ionicons pour cohérence Design System.
//
// Usage :
//   <Icon name="wrench" size={20} color={colors.primary} />
//   <Icon name="star" size={24} />
//
// Toutes les icônes passent par ce wrapper :
// pas d'import Ionicons/Phosphor direct dans les composants.
// ─────────────────────────────────────────────────────────

import React from "react";
import {
  // ── Services / catégories ──
  Wrench,
  Scissors,
  Zap,
  Paintbrush,
  Hammer,
  Pin,
  Sparkles,
  CookingPot,
  KeyRound,
  Package,
  ShieldCheck,
  Leaf,
  Flame,
  Snowflake,
  Layers,
  Droplet,

  // ── UI / navigation ──
  Pencil,
  FileText,
  ClipboardList,
  Star,
  MessageCircle,
  Bell,
  HelpCircle,
  Info,
  Lock,
  Trash2,
  LogOut,
  Settings,
  MapPin,
  DollarSign,
  BarChart3,
  Hand,
  UserCog,
  Hourglass,
  CheckCircle,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Clock,
  Sparkle,
  Timer,
  Coins,
  Megaphone,
  Compass,
  Heart,
  Calendar,
  Mail,
  Globe,
  Languages,
  Camera,
  Image,
  CreditCard,
  MessageCircleMore,
  Send,
  Inbox,
  MessageSquare,
  Search,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  Phone,
  Flag,
  Plus,
  PlusCircle,
  X,
  Check,
  CheckCheck,
  MoreVertical,
  Gift,
  Share2,
  SlidersHorizontal,
  Tag,
  RefreshCw,
  Circle,
  Upload,
  CornerDownRight,
  Delete,
  Undo2,
  Banknote,
  Eye,
  EyeOff,
  User,
  Users,
  AlertCircle,
  PhoneCall,
  MessagesSquare,
  Crown,
  Crosshair,
  Navigation,
  Map,
  House,
  PersonStanding,
  Wallet,
  TrendingUp,
  ArrowUpRight,
  ArrowDownLeft,
  Funnel,
  LayoutGrid,
  List,
  Bookmark,
  BookmarkCheck,
  ThumbsUp,
  Award,
  BadgeCheck,
  CircleDot,
  Play,
  Pause,
  RotateCcw,
  Wifi,
  WifiOff,
  BellRing,
  BellOff,
  Copy,
  ExternalLink,
  Link,
  Unlink,
  Briefcase,
  Percent,
  Images,
} from "lucide-react-native";
import { colors } from "../../theme";

// ── Mapping nom → composant Lucide ──────────────────────
// Noms kebab-case pour API simple dans les props.
// Inclut les anciens noms Phosphor + Ionicons pour migration fluide.
const ICON_MAP = {
  // ── Services ──
  "wrench":          Wrench,
  "scissors":        Scissors,
  "lightning":       Zap,
  "zap":             Zap,
  "paint-brush":     Paintbrush,
  "paintbrush":      Paintbrush,
  "hammer":          Hammer,
  "needle":          Pin,
  "pin":             Pin,
  "broom":           Sparkles,
  "sparkles":        Sparkles,
  "cooking-pot":     CookingPot,
  "key":             KeyRound,
  "package":         Package,
  "shield-check":    ShieldCheck,
  "plant":           Leaf,
  "leaf":            Leaf,
  "flame":           Flame,
  "snowflake":       Snowflake,
  "wall":            Layers,
  "layers":          Layers,
  "drop":            Droplet,
  "droplet":         Droplet,

  // ── Menu / Profile ──
  "pencil-simple":   Pencil,
  "pencil":          Pencil,
  "file-text":       FileText,
  "clipboard-text":  ClipboardList,
  "star":            Star,
  "chat-circle":     MessageCircle,
  "message-circle":  MessageCircle,
  "bell":            Bell,
  "question":        HelpCircle,
  "help-circle":     HelpCircle,
  "info":            Info,
  "lock":            Lock,
  "trash":           Trash2,
  "sign-out":        LogOut,
  "log-out":         LogOut,
  "gear":            Settings,
  "settings":        Settings,
  "map-pin":         MapPin,
  "location":        MapPin,
  "currency-dollar": DollarSign,
  "dollar-sign":     DollarSign,
  "chart-bar":       BarChart3,
  "bar-chart":       BarChart3,
  "hand-waving":     Hand,
  "hand":            Hand,
  "user-switch":     UserCog,
  "user-cog":        UserCog,
  "hourglass":       Hourglass,
  "check-circle":    CheckCircle,
  "check-circle-2":  CheckCircle2,
  "x-circle":        XCircle,
  "warning":         AlertTriangle,
  "alert-triangle":  AlertTriangle,
  "alert-circle":    AlertCircle,
  "clock":           Clock,
  "sparkle":         Sparkle,
  "timer":           Timer,
  "hand-coins":      Coins,
  "coins":           Coins,
  "megaphone":       Megaphone,
  "compass":         Compass,
  "heart":           Heart,
  "calendar":        Calendar,
  "envelope":        Mail,
  "mail":            Mail,

  // ── Provider / setup ──
  "globe":           Globe,
  "translate":       Languages,
  "languages":       Languages,
  "camera":          Camera,
  "image":           Image,
  "identification-card": CreditCard,
  "credit-card":     CreditCard,

  // ── Chat / messaging ──
  "chat-circle-dots": MessageCircleMore,
  "chat-teardrop-dots": MessageSquare,
  "message-square":  MessageSquare,
  "paper-plane":     Send,
  "send":            Send,

  // ── Empty states ──
  "tray-arrow-down": Inbox,
  "inbox":           Inbox,
  "magnifying-glass": Search,
  "search":          Search,

  // ── Navigation ──
  "caret-right":     ChevronRight,
  "chevron-right":   ChevronRight,
  "chevron-back":    ChevronLeft,
  "chevron-left":    ChevronLeft,
  "chevron-down":    ChevronDown,
  "chevron-up":      ChevronUp,
  "chevron-forward": ChevronRight,
  "arrow-left":      ArrowLeft,
  "arrow-back":      ArrowLeft,
  "arrow-right":     ArrowRight,
  "phone":           Phone,
  "call-outline":    PhoneCall,
  "phone-call":      PhoneCall,
  "flag":            Flag,

  // ── Actions ──
  "plus":            Plus,
  "add":             Plus,
  "plus-circle":     PlusCircle,
  "add-circle-outline": PlusCircle,
  "close":           X,
  "x":               X,
  "close-circle":    XCircle,
  "close-circle-outline": XCircle,
  "check":           Check,
  "checkmark":       Check,
  "checkmark-done":  CheckCheck,
  "check-check":     CheckCheck,
  "checkmark-circle-outline": CheckCircle,
  "more-vertical":   MoreVertical,
  "ellipsis-vertical": MoreVertical,
  "gift":            Gift,
  "gift-outline":    Gift,
  "share":           Share2,
  "share-social-outline": Share2,
  "sliders":         SlidersHorizontal,
  "options":         SlidersHorizontal,
  "tag":             Tag,
  "pricetag-outline": Tag,
  "refresh":         RefreshCw,
  "circle":          Circle,
  "ellipse":         Circle,
  "upload":          Upload,
  "cloud-upload-outline": Upload,
  "corner-down-right": CornerDownRight,
  "return-down-forward-outline": CornerDownRight,
  "delete":          Delete,
  "backspace-outline": Delete,
  "undo":            Undo2,
  "arrow-undo":      Undo2,
  "banknote":        Banknote,
  "cash-outline":    Banknote,
  "eye":             Eye,
  "eye-off":         EyeOff,
  "user":            User,
  "users":           Users,

  // ── Ionicons aliases (pour migration fluide) ──
  "notifications":   Bell,
  "construct-outline": Wrench,
  "document-text":   FileText,
  "document-text-outline": FileText,
  "flash":           Zap,
  "heart-outline":   Heart,
  "location-outline": MapPin,
  "search-outline":  Search,
  "settings-outline": Settings,
  "star-outline":    Star,
  "time-outline":    Clock,
  "trash-outline":   Trash2,
  "warning-outline": AlertTriangle,
  "chatbubble-ellipses": MessageCircle,
  "chatbubbles-outline": MessagesSquare,
  "calendar-outline": Calendar,
  "camera-outline":  Camera,

  // ── Ajouts DS v2 (Map, badges, navigation) ──
  "crown":           Crown,
  "crosshair":       Crosshair,
  "navigation":      Navigation,
  "map":             Map,
  "home":            House,
  "house":           House,
  "person":          User,
  "chatbubble":      MessageCircle,
  "chatbubble-outline": MessageCircle,
  "wallet":          Wallet,
  "trending-up":     TrendingUp,
  "arrow-up-right":  ArrowUpRight,
  "arrow-down-left": ArrowDownLeft,
  "filter":          Funnel,
  "funnel":          Funnel,
  "layout-grid":     LayoutGrid,
  "list":            List,
  "bookmark":        Bookmark,
  "bookmark-check":  BookmarkCheck,
  "thumbs-up":       ThumbsUp,
  "award":           Award,
  "badge-check":     BadgeCheck,
  "circle-dot":      CircleDot,
  "play":            Play,
  "pause":           Pause,
  "rotate-ccw":      RotateCcw,
  "wifi":            Wifi,
  "wifi-off":        WifiOff,
  "bell-ring":       BellRing,
  "bell-off":        BellOff,
  "copy":            Copy,
  "external-link":   ExternalLink,
  "link":            Link,
  "unlink":          Unlink,
  "sliders-horizontal": SlidersHorizontal,
  "briefcase":       Briefcase,
  "percent":         Percent,
  "images":          Images,
  "images-outline":  Images,
  "refresh-cw":      RefreshCw,
  "mail-outline":    Mail,
};

export default function Icon({
  name,
  size = 20,
  color = colors.ink900,
  strokeWidth = 2,
  style,
  // `weight` ignoré (rétro-compat Phosphor — Lucide est toujours outlined)
  weight,
}) {
  const IconComponent = ICON_MAP[name];
  if (!IconComponent) {
    if (__DEV__) console.warn(`[Icon] Icône inconnue: "${name}"`);
    return null;
  }
  return (
    <IconComponent
      size={size}
      color={color}
      strokeWidth={strokeWidth}
      style={style}
    />
  );
}

// Export pour usage conditionnel (ex: vérifier si un nom existe)
export { ICON_MAP };
